Instagramp 2/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using RegisterAndLoginApp.Models;
using RegisterAndLoginApp.Service;

namespace RegisterAndLoginApp.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ProcessLogin(UserModel user)
        {
            SecurityService securityService = new SecurityService();

            if (securityService.IsValid(user))
            {//add a popup that says logged in
                return RedirectToAction("Index","Home");
            }
            else
            {
                return View("LoginFailure", user);
            }
        }

        public IActionResult ProcessRegister(UserModel user)
        {
            return View();
        }

        public IActionResult RegisterResults(UserModel user)
        {

            SecurityService securityService = new SecurityService();
            SecurityDAO securityDAO = new SecurityDAO();

            // Here I check if the user is already in the database 
            // if they are it doesnt register the user
            // if they are not then it creates the user
            if (securityService.IsValid(user))
            {
                return View("LoginFailure", user);
            }
            else
            {
                securityDAO.Create(user);
                return View("RegisterSuccess", user);
            }
            
        }
    }
}

Instagramp 2/Controllers/ProfileController.cs
using System.Text;
using ClassLibrary;
using Instagramp_2.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;

namespace Instagramp_2.Controllers
{
    public class ProfileController : Controller
    {
        PostDAO repo = new PostDAO();
        public IActionResult Index()
        {

            return View(repo.GetAll());
        }
        public IActionResult UploadImage()
        {
            return View("Upload");
        }

        public IActionResult PostSuccess(PostModel post)
        {
            // convert image to bits:
            //string imgRef = post.ImgURL;
            //byte[] imageBytes = System.IO.File.ReadAllBytes(post.ImgURL);
            //post.ImgURL = imageBytes.ToString();
            //Console.WriteLine(imageBytes.ToString());
            repo.Create(post);

            // delete local file
            //System.IO.File.Delete(imgRef);
            return View("Index", repo.GetAll());
        }

        [HttpPost]
        public async Task<IActionResult> ProcessUpload(IFormFile file)
        {
            if (file == null || file.Length == 0)
            {
                ModelState.AddModelError("", "Please select a file to upload.");
                return View();
            }

            var fileName = Path.GetFileName(file.FileName);
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads", fileName);

            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }
            ViewBag.Message = "File uploaded successfully.";



            byte[] imageBytes = System.IO.File.ReadAllBytes(filePath);
            string stringBytes = Convert.ToBase64String(imageBytes);
            ViewBag.FilePath = stringBytes;
            //Console.WriteLine(stringBytes);
            //ViewBag.FilePath = $"/uploads/{fileName}";
            System.IO.File.Delete(filePath);
            return View("AddPost");
        }

        public IActionResult AddPost()
        {
            return View();
        }
    }
}

Instagramp 2/Controllers/SearchController.cs
using ClassLibrary;
using Instagramp_2.Models;
using Instagramp_2.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;

namespace Instagramp_2.Controllers
{
    public class SearchController : Controller
    {
        private readonly IPostDAO _postDAO;
        public SearchController(IPostDAO postDAO)
        {
            _postDAO = postDAO;
        }
        public IActionResult Index()
        {
            List<SearchTermModel> searchTerms = new List<SearchTermModel>();

            searchTerms.Add(new SearchTermModel("Family", "See posts about family!", "img/familypic.jpg"));
            searchTerms.Add(new SearchTermModel("Friends", "See posts about friends!", "img/dawgsoutpic.jpg"));
            searchTerms.Add(new SearchTermModel("Nature", "See posts about nature!", "img/naturepic.jpg"));
            searchTerms.Add(new SearchTermModel("Sports", "See posts about sports!", "img/sportspic.jpg"));
            searchTerms.Add(new SearchTermModel("Food", "See posts about food!", "img/foodpic.jpg"));
            searchTerms.Add(new SearchTermModel("Other", "See posts about all other topics!", "img/otherpic.jpg"));

            return View(searchTerms);
        }

        public IActionResult Filter(string categories)
        {
            // Redirect to the appropriate category action method based on selected categories
            if (categories.Contains("Family"))
            {
                return RedirectToAction("Family", new { categories = categories });
            }
            else if (categories.Contains("Friends"))
            {
                return RedirectToAction("Friends", new { categories = categories });
            }
            else if (categories.Contains("Nature"))
            {
                return RedirectToAction("Nature", new { categories = categories });
            }
            else if (categories.Contains("Sports"))
            {
                return RedirectToAction("Sports", new { categories = categories });
            }
            else if (categories.Contains("Food"))
            {
                return RedirectToAction("Food", new { categories = categories });
            }
            else if (categories.Contains("Other"))
            {
                return RedirectToAction("Other", new { categories = categories });
            }

            // If no categories are selected, you can handle it as desired (e.g., return an error view)
            return RedirectToAction("NoSearchTerms");
        }

        public IActionResult Family(string categories)
        {
            List<PostModel> filteredPosts = _postDAO.GetAll()
                .Where(p => categories.Contains(p.Category.ToString()))
                .ToList();

            return View(filteredPosts);
        }
        public IActionResult Friends(string categories)
        {
            List<PostModel> filteredPosts = _postDAO.GetAll()
                .Where(p => categories.Contains(p.Category.ToString()))
                .ToList();

            return View(filteredPosts);
        }
        public IActionResult Nature(string categories)
        {
            List<PostModel> filteredPosts = _postDAO.GetAll()
                .Where(p => categories.Contains(p.Category.ToString()))
                .ToList();

            return View(filteredPosts);
        }
        public IActionResult Sports(string categories)
        {
            List<PostModel> filteredPosts = _postDAO.GetAll()
                .Where(p => categories.Contains(p.Category.ToString()))
                .ToList();

            return View(filteredPosts);
        }
        public IActionResult Food(string categories)
        {
            List<PostModel> filteredPosts = _postDAO.GetAll()
                .Where(p => categories.Contains(p.Category.ToString()))
                .ToList();

            return View(filteredPosts);
        }
        public IActionResult Other(string categories)
        {
            List<PostModel> filteredPosts = _postDAO.GetAll()
                .Where(p => categories.Contains(p.Category.ToString()))
                .ToList();

            return View(filteredPosts);
        }
    }
}


  

Instagramp 2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RegisterAndLoginApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/RegisterAndLoginApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="position:fixed; width: 100%;">
            <div>
                <img class="logo" src="~/img/InstagrampLogo.png" alt="Logo">
            </div>
            <div class="container-fluid">
                <a class="logo-words" asp-area="" asp-controller="Home" asp-action="Index">Instagramp 2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Search" asp-action="Index">Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Profile" asp-action="Index">Profile</a>
                        </li>
                    </ul>
                    <ul class ="nav justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RegisterAndLoginApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>